# Generated by Django 5.0.1 on 2024-02-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=60)),
                ('DOB', models.DateField()),
                ('nationality', models.CharField(choices=[('Nepal', 'Nepal'), ('India', 'India'), ('China', 'China'), ('Pakistan', 'Pakistan'), ('Bangladesh', 'Bangladesh'), ('USA', 'USA'), ('UK', 'UK')], max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=60)),
                ('university', models.CharField(max_length=50)),
                ('Graduated_year', models.DateField()),
                ('skills', models.TextField()),
                ('about_you', models.TextField()),
                ('Experience', models.TextField()),
                ('previous_work', models.TextField()),
            ],
        ),
    ]
