# Generated by Django 5.0.1 on 2024-02-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
