# Generated by Django 5.0.1 on 2024-02-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0003_profile_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pdf_file',
        ),
    ]
