# Generated by Django 5.0.1 on 2024-02-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0004_remove_profile_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(blank=True),
        ),
    ]
