# Generated by Django 5.0.1 on 2024-02-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0009_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
